/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controladores.AnalizadorVocales;
import Controladores.TNumeros;
import java.awt.Image;
import java.io.Reader;
import java.io.StringReader;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emili
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    ImageIcon Boton1 = new ImageIcon("jugar.png");
    ImageIcon Boton2 = new ImageIcon("Borrar.png");
    ImageIcon Alerta = new ImageIcon("Error.png");
    ImageIcon Fondo = new ImageIcon("fondo.jpg");
    public Inicio() {
        initComponents();
        Transparencia();
        Limpiar.setIcon(new ImageIcon(Boton2.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        Ejecutar.setIcon(new ImageIcon(Boton1.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        alertas.setIcon(new ImageIcon(Alerta.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        fondo.setIcon(new ImageIcon(Fondo.getImage().getScaledInstance(644, 550, Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textArea = new javax.swing.JTextArea();
        jList1 = new javax.swing.JList<>();
        tablanum = new javax.swing.JTable();
        Ejecutar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        alertas = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textArea.setColumns(20);
        textArea.setRows(5);
        jPanel1.add(textArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 590, 150));

        jPanel1.add(jList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 290, 136));

        tablanum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jPanel1.add(tablanum, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 290, 120));

        Ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarActionPerformed(evt);
            }
        });
        jPanel1.add(Ejecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, 60));

        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 80, 60));
        jPanel1.add(alertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 100, 60));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 635, 501));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarActionPerformed
        // TODO add your handling code here:
        Reader reader = new StringReader(this.textArea.getText());
        AnalizadorVocales Analizar = new AnalizadorVocales();
        if (Analizar.getPalabras(reader)) {
        
            int[] valuesVocal = Analizar.getContadorV();
            ArrayList<TNumeros> numbersInfo = Analizar.getInfoNumero();
        
        
          VocalesInfo(valuesVocal);
          NumerosInfo(numbersInfo);
        }
    }//GEN-LAST:event_EjecutarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_LimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
 private void VocalesInfo(int[] valuesVocal) {
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < valuesVocal.length - 1; i++) {
            listModel.addElement((i + 1) + " vocal(es): " + valuesVocal[i]); // add items
        }
        // add the 0 vowels
        listModel.addElement("0 o 6+ vocales: " + valuesVocal[5]);
        // set new model
        this.jList1.setModel(listModel);
    }

    private void NumerosInfo(ArrayList<TNumeros> numbersInfo) {
        // clear table
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Numero");
        tableModel.addColumn("Fila");
        tableModel.addColumn("Columna");
        for (TNumeros numberToken : numbersInfo) {
            tableModel.insertRow(0, new Object[]{numberToken.getValue(), numberToken.getLine(), numberToken.getColumn()});
        }
        // set new model
        this.tablanum.setModel(tableModel);
    }
    public void Transparencia(){
        Limpiar.setOpaque(false);
        Limpiar.setContentAreaFilled(false);
        Ejecutar.setOpaque(false);
        Ejecutar.setContentAreaFilled(false);
    }
    public void Limpiar(){
    textArea.setText(null);
    jList1.clearSelection();
    tablanum.clearSelection();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ejecutar;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel alertas;
    private javax.swing.JLabel fondo;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tablanum;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
